name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Restore dependencies
      run: dotnet restore src/SamplePollyRefit.sln

    - name: Build
      run: dotnet build src/SamplePollyRefit.sln --no-restore

    - name: Test
      run: dotnet test src/SamplePollyRefit.sln --no-build --verbosity normal

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build :latest
      run: docker build . -f /SampleRefitWithRetry/src/SamplePollyRefit/Dockerfile -t marcelomws/sample-refit:latest -f /src/SamplePollyRefit/

    - name: Push to docker hub :latest
      uses: actions-hub/docker@master
      with:
        args: push marcelomws/sample-refit:latest
